### ISSUE TITLE
Error: "The front of this card is blank"

### ISSUE THREAD

**Issue by edofe99** [ssricardo/anki-plugins#61] opened 2020-03-24 16:07 UTC
Hi, I downloaded the plugin and followed the instruction and I keep receiving the errors like the image below: 
![Schermata 2020-03-24 alle 16 59 49](https://user-images.githubusercontent.com/62611612/77448816-88ecfd00-6df1-11ea-9109-8150d8dde96c.png)

As you can see the front is not blank at all, and this message goes away if I remove "type" : 

![Schermata 2020-03-24 alle 17 05 28](https://user-images.githubusercontent.com/62611612/77448931-ab7f1600-6df1-11ea-89a8-d8e8dc19bc37.png)
 
How can I solve this? I would like to use this plugin because it can be really useful for me. 

Thank's, have a nice day.

**Comment by edofe99** [comment] 2020-03-24 16:22
Edit: I had to add a field before the one used for "fill the blank". It worked. 


![Schermata 2020-03-24 alle 17 21 55](https://user-images.githubusercontent.com/62611612/77450792-10d40680-6df4-11ea-8ae6-f5c03fa16eb3.png)

**Comment by ssricardo** [comment] 2020-03-25 11:57
Hey @ironhak , I'm testing it.
Meanwhile, what's you Anki's version?

**Comment by edofe99** [comment] 2020-03-25 12:53
Hi
Version 2.1.23 (de9543ff) I'm running it on mac.

Have a nice day

**Comment by ssricardo** [comment] 2020-03-25 13:24
Hi. I couldn't reproduce it. 
Unfortunately that version is available only for Mac so far. And as I don't have one, I can test it yet. 

Then, please wait until I can get and run on that version...

**Comment by edofe99** [comment] 2020-03-25 13:28
Don't worry, I simply "fixed" that adding an extra field so I can use your add-on without any problem.

**Comment by ssricardo** [comment] 2020-03-25 17:06
Thank you! 
Let's keep this issue open, then I'll fix it when I get the new release

**Comment by ssricardo** [comment] 2020-03-25 22:47
Could you also export this deck, or a small sample deck on which this happens please?

I think that's weird, because I even compared Anki's code on current version with the previous ones, and the area that this addon works wasn't changed...

**Comment by edofe99** [comment] 2020-03-26 11:17
For sure, here it is. This is a sample deck I've created, there is only one card witch is a cloze card type. From the image you can see how my anki app display the error. 

[Samoke_deck.zip](https://github.com/ssricardo/anki-plugins/files/4386803/Samoke_deck.zip)

![Schermata 2020-03-26 alle 12 13 14](https://user-images.githubusercontent.com/62611612/77641025-a5a54400-6f5b-11ea-90f8-447514199997.png)

Also you can try for yourself to add a field positioned before the one used for the text and you'll see that everything will work fine.

**Comment by ssricardo** [comment] 2020-03-26 16:56
Yeah, it's indeed something with the newer version.

Just checked it here:

![Anki-tester](https://user-images.githubusercontent.com/28906929/77673906-16b02000-6f8b-11ea-8445-f1c135e8b7e5.png)

**Comment by edofe99** [comment] 2020-03-26 17:06
Oh I got it, anyway just after I created the sample deck for you a new issue come, as you can see from the photo I can only see a blank box

![Schermata 2020-03-26 alle 18 06 10](https://user-images.githubusercontent.com/62611612/77674855-7a871880-6f8c-11ea-92e4-54e4370601ba.png)

What version of anki should I download in order to get this to work? I really need this addon

**Comment by ssricardo** [comment] 2020-03-26 20:30
I have it running with .20 and .21.

But on this "Card type..." editor, it shows like that (with a single field). You need to run the reviewer to indeed check it

**Comment by miieandering** [comment] 2020-03-27 01:40
Hello! I'm new to github so I'm not sure if I need to open a separate thread on this, but I tried Ironhak's first solution of adding an extra field in front of the text field, and it's worked so far (I'm running Anki 2.1.23 as well):

<img width="757" alt="Screen Shot 2020-03-27 at 9 38 11 AM" src="https://user-images.githubusercontent.com/58385932/77712461-cda1af80-700e-11ea-9aa6-d5e06d2dc567.png">
<img width="405" alt="Screen Shot 2020-03-27 at 9 38 21 AM" src="https://user-images.githubusercontent.com/58385932/77712467-d09ca000-700e-11ea-8449-e92bd2a373db.png">
<img width="959" alt="Screen Shot 2020-03-27 at 9 38 28 AM" src="https://user-images.githubusercontent.com/58385932/77712468-d1353680-700e-11ea-91bf-2437fa54ecc4.png">

The extra field in front of the text field must have some form of text in it as well, or else the card shows up as "The front of this card is blank". (Edit: the normal {{Cloze:Text}} in the back side of the card works as well). Hope this helps and feel free to let me know if you need more information.

Edit # 2: I downloaded a batch editor and just shoved in some text in the newly created "extra" field for the cards that I needed to use. So far it's been working.
<img width="1424" alt="Screen Shot 2020-03-27 at 7 01 52 PM" src="https://user-images.githubusercontent.com/58385932/77749811-a0c8b900-705d-11ea-919c-de7c8848947d.png">
<img width="968" alt="Screen Shot 2020-03-27 at 7 04 18 PM" src="https://user-images.githubusercontent.com/58385932/77749984-f1d8ad00-705d-11ea-88b2-ee58e8a96dd0.png">

**Comment by edofe99** [comment] 2020-03-27 09:13
I've tried to download Anki 2.1.15 but instead of working there's a new bug 
![Schermata 2020-03-27 alle 10 06 51](https://user-images.githubusercontent.com/62611612/77740072-e744f600-7012-11ea-9281-5ff43fca699f.png)

If I click tools>empty cards anky display a message that say "no empty cards". Probably it is a problem with the mac version. 

@miieandering I tried your method but this simply create a box under the sentence showing the solution. The addon should create the box in the middle of the sentence or wherever you placed {{c1::...}}. 

I don't know why I made it working perfectly for a couple of hours with the "fix" of adding a field and now it don't work.

**Comment by ssricardo** [comment] 2020-03-27 16:44
Hey! 
I've got it also, now on version .22.  It's a problem on Anki directly (you can check it, by removing the add-on).  

It happens before the add-on get processed, then I already receive the content with that message instead of the original card content. 

I also wrote a small note here: https://github.com/ssricardo/anki-plugins/wiki/Temp---Anki-problem-with-type

**Comment by joselpg** [comment] 2020-04-16 01:00
Hi @ssricardo . I would like to know if you're still working with this add-on for the newer version of Anki. I couldn't use it. But I think it's one of the most powerfull add-on for anki. Or do you have a pro version, or something like that?. You are the best friend!

**Comment by ssricardo** [comment] 2020-04-16 07:41
Hi @joselpg! 

As I mentioned just above:

> It's a problem on Anki directly (you can check it, by removing the add-on).
> 
> It happens before the add-on get processed, then I already receive the content with that message instead of the original card content.
> 
> I also wrote a small note here: https://github.com/ssricardo/anki-plugins/wiki/Temp---Anki-problem-with-type
> 

That means, there is nothing that I can do unfortunately. 
Except wait for next Anki release...

**Comment by joselpg** [comment] 2020-04-16 19:20
Hi  @ssricardo. Ok, I understand. I have it clearer now. I thought it was a simple code update problem, compared to the new version. Well, hopefully Anki somehow fixes that part. Thanks friend.

**Comment by ssricardo** [comment] 2020-06-14 10:09
Closing as it's working on current version

**Closed as completed by ssricardo** 2020-06-14 10:09 UTC
