### ISSUE TITLE
Fill the blanks and AnkiDroid

### ISSUE THREAD

**Issue by g-collain** [ssricardo/anki-plugins#41] opened 2020-01-04 13:57 UTC
Hello!

"Fill the blanks" add-on is very useful, it's great thank you!
Unfortunately, it breaks my cards when I study them on AnkiDroid app… It appears as a blank card and asks me to type the answer. I don't really know how it could be fixed. Maybe I could add something in the card model to make it appear as a normal "cloze" card in AnkiDroid.
I think I'll just learn on my computer until I find something.

Thanks a lot :)

**Comment by ssricardo** [comment] 2020-01-05 11:57
Hey @Caernide !

Basically AnkiDroid behaves like Anki without the Add-on. 
The problem is that these add-ons are not supported by the Android app.

I have the same problem when I want to review my card on my cell phone...
But unfortunately I can't do anything about it.

I you have any possible ideas, let me know

**Comment by g-collain** [comment] 2020-01-06 07:43
Well, I found an ugly trick to be able to review the cards on Android. I just changed the template from ``{{type:cloze:Texte}}`` to  ``{{type:cloze:Texte}} <hr> {{cloze:Texte}}``. On the computer it shows the card twice, and on the phone I have the lines ------ plus the normal cloze text. It's not very beautiful but it works :)

**Comment by ssricardo** [comment] 2020-01-06 18:01
Humm, interesting.
I'll close this ticket for now (as I can't do anything about it specifically, but I guess I can do something around your comment later. 

For instance, customize the expression replaced with _input fields_, maybe accepting {{cloze:Texte}} without "type:". It'd required some work, but that's an idea...

**Closed as completed by ssricardo** 2020-01-06 18:01 UTC
