### ISSUE TITLE
No longer can right click within anki browser

### ISSUE THREAD

**Issue by weanprednisone** [ssricardo/anki-plugins#18] opened 2019-05-22 03:00 UTC
Right click is fine to bring up the anki browser, but when I go into google images, it no longer right clicks to show import into field. 

I've reinstalled the add-on, restarted anki & my computer. I have no right click mouse issues elsewhere.

**Comment by ssricardo** [comment] 2019-05-22 11:40
Hey @weanprednisone. 
What is the version of your Anki?
What is the URL of the image that it didn't work?

**Comment by weanprednisone** [comment] 2019-05-23 05:39
I use google images
Anki 2.1
It has worked, but stopped working for some reason. Thanks for replying!

**Comment by shahrokh-bahtooei** [comment] 2019-05-23 09:47
Hi,
I do also have the same problem with using "Assign to field" feature on "Google Images" for copying them to "Extra" field of "Cloze" card type. 
Please fix it as soon as possible.

------------------------------
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.12 (eef86bf3) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.4
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Anki Web Browser Selection searching Import texts and images automatically

Caught exception:
  File "/Users/Shahrokh/Library/Application Support/Anki2/addons21/864545277/browser.py", line 191, in <lambda>
    return lambda: self._selectedListener.handleSelection(field, value, isLink)
  File "/Users/Shahrokh/Library/Application Support/Anki2/addons21/864545277/controller.py", line 175, in handleSelection
    self.handleUrlSelection(fieldIndex, value)
  File "/Users/Shahrokh/Library/Application Support/Anki2/addons21/864545277/controller.py", line 188, in handleUrlSelection
    Feedback.log('handleUrlSelection.imgReference: ' + imgReference)
<class 'TypeError'>: must be str, not NoneType

**Comment by ssricardo** [comment] 2019-05-23 21:21
Thanks for the reports guy, i'm already trying to check that

**Comment by ssricardo** [comment] 2019-05-31 21:52
A new release is available (1.2) which handles this issue. 
It doesn't solve what you want completely, because it's **not a bug** on the addon. 

What happens:
* The addon uses Anki engine to import the images
* Anki has a restriction that it accepts only URLs with static files. More precisely URLs with one these suffix: (png, jpg, jpeg, git). 

> Check it out: https://github.com/dae/anki/blob/master/aqt/editor.py#L624

* Google Images probably changed something on their links to the images.

--------------
I got to import from Google Images yet, but it required the following steps:
* Click on the thumbnail
  * It's going to focus on the image, but it puts an extra parameter in the end (like https://mysite.com/coffee.png?width=med
* Click again on that image
* Now it was possible to import it

**Closed as completed** 2019-06-06 03:55 UTC
