### ISSUE TITLE
fill-the-blanks With code using curly braces.

### ISSUE THREAD

**Issue by etrekell** [ssricardo/anki-plugins#85] opened 2021-02-28 21:50 UTC
When using the add-on to fill in code that uses curly braces, the cloze syntax interferes. 
For example, if you wanted to test by filling in the first code in this snippet:

Code you want to test yourself on:
```
function fun() {
  // do something
}
```
In anki: 
```
{{c1::function fun() {}}
  // do something
}
```

The opening curly brace messes it up. Do you know any way around this?

**Comment by ssricardo** [comment] 2021-03-03 20:41
Hi! 
Unfortunately I don't know a good way to use that. 
The problem is likely because it matches Anki "reserved" grammar, so that this `}}` is used on some regex. 
So the regex is likely  taking your typed `}}`.

I'd try a simple workaround, which is: just add a space between them. Like: `} }`

**Comment by ssricardo** [comment] 2021-04-09 20:07
I'm closing this for now, because I don't a way around this, ok?!
Unfortunately it's a limitation due to how Anki works...

**Closed as completed by ssricardo** 2021-04-09 20:07 UTC

**Comment by etrekell** [comment] 2021-04-09 20:12
Yep, thanks!
